### ISSUE TITLE
Examples should be renamed to match lib name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_MCP3xxx#15]
Currently the examples begin with `mcp3004_` and `mcp3008_`. They should begin with `mcp3xxx_` to follow CircuitPython library standards. These examples should be renamed to begin with `mcp3xxx_mcp3004_` and `mcp3xxx_mcp3008_`. It's longer, but it will better identify which library these examples are associated with in the library example bundle.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by brentru** [comment]
Merged and released, thanks @magnusvmt!
