### ISSUE TITLE
differential python code with 2 sensors

### ISSUE THREAD

**Issue by grektor** [adafruit/Adafruit_CircuitPython_MCP3xxx#26]
import time
import Adafruit_GPIO.SPI as SPI
import Adafruit_MCP3008
SPI_PORT = 0
SPI_DEVICE = 0
mcp = Adafruit_MCP3008.MCP3008(spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE))
print('Press Ctrl-C to quit...')
while True:
    value = mcp.read_adc_difference(0)
    print(format(value))
    time.sleep(0.0)

I would like to kindly ask your help!
I would like to setup a circuit with 2 FSR sensors. The code above is perfectly working with one FSR, but I have difficulties adjusting the code to read also the signal of the 2nd FSR sensor. Could you give me your advice!? Thank you!

**Comment by caternuson** [comment]
Your code looks like it using the older deprecated library. For use with this library, see example here:
https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx/blob/master/examples/mcp3xxx_mcp3008_differential_simpletest.py
and general info here:
https://learn.adafruit.com/mcp3008-spi-adc/python-circuitpython

Using 2 FSRs sensors should just be a matter of wiring and using 2 differential (or single ended) channels.
