### ISSUE TITLE
How can i read measurements from pH sensor?

### ISSUE THREAD

**Issue by muhamedsuhail** [adafruit/Adafruit_CircuitPython_MCP3xxx#33]
I am using mcp3008 to read analog input from the E-201C pH sensor. I am trying to interpret pH values from voltage measurements. But, wherever I search, the results are like converting mv readings obtained from pH sensor to pH readings.
`chan = AnalogIn(mcp, MCP.P0);print(chan.voltage)`
Does the above code produce mV readings or V readings? Is there anything you can help me to measure pH sensor reading through mcp3008 to the raspberry pi?

**Comment by ladyada** [comment]
tech support questions should go to the place you purchased your pH sensor first, pleaes contant them for example code for Raspbery Pi!
