### ISSUE TITLE
spi1 instead of spi0

### ISSUE THREAD

**Issue by Schmediii** [adafruit/Adafruit_CircuitPython_MCP3xxx#34]
Sorry that i write this in the Issues but i have a question.
I want to use your code to read analog inputs with a raspi with the MCP3008. But not with the spi0 but with the spi1, is this possible and how can i change this? For example in the code of mcp3xxx_mcp3008_single_ended_simpletest.py.
Thank you for your help.

**Comment by jposada202020** [comment]
@Schmediii Please use the Adafruit Discord Channel for these kind of questions, you will get more visibility and probably more answers. or the Adafruit Forums if you like. Thanks

**Comment by benocd** [comment]
Hey @Schmediii did you find the solution for this?

**Comment by tekktrik** [comment]
Yes, it is possible using Blinka on a Raspberry Pi.  For more help or information, please use the previously mentioned resources.  Thanks!
