### ISSUE TITLE
Using 2 x MCP3008 chips

### ISSUE THREAD

**Issue by benocd** [adafruit/Adafruit_CircuitPython_MCP3xxx#36]
Hi, I'm trying to connect 2 x MCP3008 to a Raspberry Pi 4 but I'm only getting readings from the first chip. I'm using the same pins for CLK, MISO, MOSI and one MCP3008 connected to CS0 and the other one to CS1 on the Raspberry Pi. How can I read data from the second sensor?

**Comment by ladyada** [comment]
use any pin OTHER than CS1
