### ISSUE TITLE
RTD API Page Doesn't Render

### ISSUE THREAD

**Issue by sommersoft** [adafruit/Adafruit_CircuitPython_MCP3xxx#7]
During review of [ADS1x15 PR #19](https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/pull/19), I was comparing docstrings/RTD and noticed that the API doesn't render for MCP3xxx. `docs/api.rst` needs to be updated to:

```

.. automodule:: adafruit_mcp3xxx.adafruit_mcp3xxx
   :members:

.. automodule:: adafruit_mcp3xxx.adafruit_mcp3004
   :members:

.. automodule:: adafruit_mcp3xxx.adafruit_mcp3008
   :members:

.. automodule:: adafruit_mcp3xxx.analog_in
   :members:

```

**Comment by dherrada** [comment]
Fixed in #14. Closed.
